runtime: python311  # Specifies the Python runtime version

entrypoint: gunicorn -b :$PORT app:app  # Command to start your Flask app using Gunicorn

handlers:
- url: /static
  static_dir: static  # Serves static files from the 'static' directory

- url: /.*
  script: auto  # All other URLs are handled by the Flask app
